# Generated by Django 3.2.8 on 2021-11-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_generator', '0002_auto_20211115_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='apkg_file',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
