# Generated by Django 3.2.8 on 2021-11-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_generator', '0003_alter_post_apkg_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exact_log',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lang_log',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sound_log',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
