# Generated by Django 3.2.8 on 2021-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_generator', '0004_auto_20211117_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='input_box',
        ),
        migrations.AddField(
            model_name='post',
            name='output_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
